project:
  type: website

execute:
  freeze: auto
  
website:
  title: "Cao Wei's mlr3hf Journey"
  description: "GSoC 2026 mlr3hf Project Reports"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Easy Task"
        href: entry_tasks/easy/live_report/easy_task_live_report.qmd
      - text: "Hard Task"
        href: entry_tasks/hard/live_report/hard_live_report.qmd

format:
  html:
    theme: cosmo
    toc: true
